### ISSUE TITLE
co.paralleluniverse.strands.OwnedSynchronizer cannot be cast to co.paralleluniverse.strands.channels.QueueIntChannel

### ISSUE THREAD

**Issue by maoxianfly** [puniverse/quasar-gradle-template#1]
AOT test : 

Failed test test [com.flhx.test.quasarTest.QuasarIncreasingEchoTest] with exception: java.util.concurrent.ExecutionException: java.lang.ClassCastException: co.paralleluniverse.strands.OwnedSynchronizer cannot be cast to co.paralleluniverse.strands.channels.QueueIntChannel
java.util.concurrent.ExecutionException: java.lang.ClassCastException: co.paralleluniverse.strands.OwnedSynchronizer cannot be cast to co.paralleluniverse.strands.channels.QueueIntChannel
	at co.paralleluniverse.fibers.Fiber.get(Fiber.java:1304)
	at com.flhx.test.quasarTest.QuasarIncreasingEchoApp.doAll(QuasarIncreasingEchoApp.java:68)
	at com.flhx.test.quasarTest.QuasarIncreasingEchoTest.test(QuasarIncreasingEchoTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: co.paralleluniverse.strands.OwnedSynchronizer cannot be cast to co.paralleluniverse.strands.channels.QueueIntChannel
	at co.paralleluniverse.strands.channels.QueueIntChannel.send(QueueIntChannel.java:72)
	at com.flhx.test.quasarTest.QuasarIncreasingEchoApp$1.run(QuasarIncreasingEchoApp.java:30)
	at com.flhx.test.quasarTest.QuasarIncreasingEchoApp$1.run(QuasarIncreasingEchoApp.java:22)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1019)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1014)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:729)
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:257)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:116)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:73)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: co.paralleluniverse.fibers.VerifyInstrumentationException: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.strands.channels.QueueIntChannel.send (QueueIntChannel.java:72 bci: 122)
	at com.flhx.test.quasarTest.QuasarIncreasingEchoApp$1.run (QuasarIncreasingEchoApp.java:30 bci: 46) **
	at com.flhx.test.quasarTest.QuasarIncreasingEchoApp$1.run (QuasarIncreasingEchoApp.java:22 bci: 1) **
	at co.paralleluniverse.fibers.Fiber.run (Fiber.java:1019 bci: 11)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014 bci: 1)
		at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1664)
		at co.paralleluniverse.fibers.Fiber.access$100(Fiber.java:78)
		at co.paralleluniverse.fibers.Fiber$1.uncaughtException(Fiber.java:118)
		at co.paralleluniverse.fibers.Fiber.onException(Fiber.java:1107)
		at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:784)
		... 8 more
	Suppressed: co.paralleluniverse.fibers.VerifyInstrumentationException: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack: 
	at co.paralleluniverse.strands.channels.QueueIntChannel.send (QueueIntChannel.java:72 bci: 122)
	at com.flhx.test.quasarTest.QuasarIncreasingEchoApp$1.run (QuasarIncreasingEchoApp.java:30 bci: 46) **
	at com.flhx.test.quasarTest.QuasarIncreasingEchoApp$1.run (QuasarIncreasingEchoApp.java:22 bci: 1) **
	at co.paralleluniverse.fibers.Fiber.run (Fiber.java:1019 bci: 11)
	at co.paralleluniverse.fibers.Fiber.run1 (Fiber.java:1014 bci: 1)
		at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1664)
		at co.paralleluniverse.fibers.Fiber.access$100(Fiber.java:78)
		at co.paralleluniverse.fibers.Fiber$1.uncaughtException(Fiber.java:118)
		at co.paralleluniverse.fibers.Fiber.onException(Fiber.java:1107)
		at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.onException(FiberForkJoinScheduler.java:323)
		at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:122)
		... 6 more

**Comment by maoxianfly** [comment]
The problem has been solved
